name: RoutinyManager
description: RoutinyManager Ultimate CEO Edition
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0 # هذا سيجلب لك خطوط آيفون دون أخطاء ملفات

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true