name: Flutter Cloud Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # تحديث لـ v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Save APK
        uses: actions/upload-artifact@v4 # هنا التغيير المهم لـ v4
        with:
          name: my-app-bundle
          path: build/app/outputs/flutter-apk/app-debug.apk
